#!/usr/bin/env bash

Base="\033["
Reset="${Base}0m"
Bold="${Base}1;"

Black="${Bold}30m"
Red="${Bold}31m"
Green="${Bold}32m"
Yellow="${Bold}33m"
Blue="${Bold}34m"
Magenta="${Bold}35m"
Cyan="${Bold}36m"
White="${Bold}37m"
BrightBlack_Gray="${Bold}90m"
BrightRed="${Bold}91m"
BrightGreen="${Bold}92m"
BrightYellow="${Bold}93m"
BrightBlue="${Bold}94m"
BrightMagenta="${Bold}95m"
BrightCyan="${Bold}96m"
BrightWhite="${Bold}97m"

echo "Test Colors Start"
echo -e "${Black}Color: Black${Reset}"
echo -e "${Red}Color: Red${Reset}"
echo -e "${Green}Color: Green${Reset}"
echo -e "${Yellow}Color: Yellow${Reset}"
echo -e "${Blue}Color: Blue${Reset}"
echo -e "${Magenta}Color: Magenta${Reset}"
echo -e "${Cyan}Color: Cyan${Reset}"
echo -e "${White}Color: White${Reset}"
echo -e "${BrightBlack_Gray}Color: BrightBlack_Gray${Reset}"
echo -e "${BrightRed}Color: BrightRed${Reset}"
echo -e "${BrightGreen}Color: BrightGreen${Reset}"
echo -e "${BrightYellow}Color: BrightYellow${Reset}"
echo -e "${BrightBlue}Color: BrightBlue${Reset}"
echo -e "${BrightMagenta}Color: BrightMagenta${Reset}"
echo -e "${BrightCyan}Color: BrightCyan${Reset}"
echo -e "${BrightWhite}Color: BrightWhite${Reset}"
echo "Test Colors End"